---
kind: pipeline
type: kubernetes
name: staging

trigger:
  branch:
    - staging

steps:
  # Build and push Docker image to AWS ECR
  - name: publish
    image: plugins/kaniko-ecr
    settings:
      create_repository: true
      registry: 795250896452.dkr.ecr.us-east-1.amazonaws.com
      repo: industrysolutions/retail-store
      dockerfile: store/Dockerfile
      context: store
      tags:
        - git-${DRONE_COMMIT_SHA:0:7}
        - staging-latest
      access_key:
        from_secret: ecr_access_key
      secret_key:
        from_secret: ecr_secret_key
    when:
      event:
        - push

  # Deploy to Staging Kanopy
  - name: deploy-staging
    image: public.ecr.aws/kanopy/drone-helm:v3
    settings:
      chart: mongodb/web-app
      chart_version: 4.25.0
      add_repos:
        - mongodb=https://10gen.github.io/helm-charts
      namespace: industrysolutions
      release: retail-store-staging
      values_files: ["environments/staging.yaml"]
      values:
        - "image.tag=git-${DRONE_COMMIT_SHA:0:7}"
        - "image.repository=795250896452.dkr.ecr.us-east-1.amazonaws.com/industrysolutions/retail-store"
        - "ingress.enabled=true"
        - "ingress.hosts[0]=retail-store.industrysolutions.staging.corp.mongodb.com"
        - "mesh.enabled=true"
        - "resources.limits.memory=1Gi"
        - "resources.limits.cpu=1000m"
        - "resources.requests.memory=512Mi"
        - "resources.requests.cpu=250m"
      api_server: https://api.staging.corp.mongodb.com
      kubernetes_token:
        from_secret: staging_kubernetes_token
    when:
      event:
        - push
      branch:
        - staging  

  # Build and push Docker image to AWS ECR for Bucket Signer microservice
  - name: publish-bucketsigner
    image: plugins/kaniko-ecr
    settings:
      create_repository: true
      registry: 795250896452.dkr.ecr.us-east-1.amazonaws.com
      repo: industrysolutions/bucket-signer
      dockerfile: microservices/bucketSigner/Dockerfile
      context: microservices/bucketSigner
      tags:
        - git-${DRONE_COMMIT_SHA:0:7}
        - staging-latest
      access_key:
        from_secret: ecr_access_key
      secret_key:
        from_secret: ecr_secret_key
    when:
      branch:
        - staging

  # Deploy Bucket Signer microservice to Staging Kanopy
  - name: deploy-bucketsigner-staging
    image: public.ecr.aws/kanopy/drone-helm:v3
    settings:
      chart: mongodb/web-app
      chart_version: 4.25.0
      add_repos:
        - mongodb=https://10gen.github.io/helm-charts
      namespace: industrysolutions
      release: bucket-signer-staging
      values_files: ["environments/staging.yaml"]
      values:
        - "image.tag=git-${DRONE_COMMIT_SHA:0:7}"
        - "image.repository=795250896452.dkr.ecr.us-east-1.amazonaws.com/industrysolutions/bucket-signer"
        - "ingress.enabled=true"
        - "ingress.hosts[0]=bucket-signer-service.staging.corp.mongodb.com"
        - "mesh.enabled=true"
        - "resources.limits.memory=1Gi"
        - "resources.limits.cpu=1000m"
        - "resources.requests.memory=512Mi"
        - "resources.requests.cpu=250m"
        - "envSecrets.MONGODB_URI=retail-store-staging"
        - "envSecrets.DB_NAME=retail-store-staging"
        - "env.GOOGLE_APPLICATION_CREDENTIALS=/etc/gcp/credential-configuration.json"
      api_server: https://api.staging.corp.mongodb.com
      kubernetes_token:
        from_secret: staging_kubernetes_token
    when:
      branch:
        - staging

---
kind: pipeline
type: kubernetes
name: production

trigger:
  branch:
    - main
  event:
    - push

steps:
  # Build and push Docker image to AWS ECR
  - name: publish
    image: plugins/kaniko-ecr
    settings:
      create_repository: true
      registry: 795250896452.dkr.ecr.us-east-1.amazonaws.com
      repo: industrysolutions/retail-store-prod
      dockerfile: store/Dockerfile
      context: store
      tags:
        - git-${DRONE_COMMIT_SHA:0:7}
        - prod-latest
      access_key:
        from_secret: ecr_access_key
      secret_key:
        from_secret: ecr_secret_key
    when:
      event:
        - push

  # Deploy to Production Kanopy
  - name: deploy-production
    image: public.ecr.aws/kanopy/drone-helm:v3
    settings:
      chart: mongodb/web-app
      chart_version: 4.25.0
      add_repos:
        - mongodb=https://10gen.github.io/helm-charts
      namespace: industrysolutions
      release: retail-store-prod
      values_files:
        - environments/production.yaml
      values:
        - "image.tag=git-${DRONE_COMMIT_SHA:0:7}"
        - "image.repository=795250896452.dkr.ecr.us-east-1.amazonaws.com/industrysolutions/retail-store-prod"
        - "ingress.enabled=true"
        - "ingress.hosts[0]=retail-store.industrysolutions.prod.corp.mongodb.com"
        - "mesh.enabled=true"
        - "resources.limits.memory=1Gi"
        - "resources.limits.cpu=1000m"
        - "resources.requests.memory=512Mi"
        - "resources.requests.cpu=250m"
      api_server: https://api.prod.corp.mongodb.com
      kubernetes_token:
        from_secret: prod_kubernetes_token
    when:
      event:
        - push