services:
  retail-store-v2:
    build:
      context: ./
      dockerfile: Dockerfile 
    image: retail-store-v2:latest
    ports:
      - "8080:8080"
    restart: always
    container_name: retail-store-v2
