
services:
  event-generator:
    build:
      context: ./microservices/dynamicPricing
      dockerfile: Dockerfile
    image: event-generator:latest
    ports:
      - "8000:8000"
    restart: always
    container_name: event-generator
  store:
    build:
      context: ./store
      dockerfile: Dockerfile
    image: leafy-store:latest
    ports:
      - "3000:3000"
    restart: always
    container_name: leafy-store