name: retail-store 

services:
  bucket-signer-retail:
    build:
      context: ./microservices/bucketSigner
      dockerfile: Dockerfile
    image: bucket-signer-microservice:latest
    ports:
      - "3456:3456"
    restart: always
    container_name: bucket-signer-microservice
  store:
    build:
      context: ./store
      dockerfile: Dockerfile
    image: leafy-store:latest
    ports:
      - "3000:3000"
    restart: always
    container_name: leafy-store