# Service Account Configuration
serviceAccount:
  enabled: true
  name: retail-store-gcp-sa  # Must match KSA_NAME

# Mount GCP credential config AND projected service account token
extraVolumes:
  - name: gcp-creds
    configMap:
      name: gcp-wif-config
  - name: gcp-token
    projected:
      sources:
      - serviceAccountToken:
          path: token
          expirationSeconds: 3600  # Token expires after 1 hour and auto-renews
          audience: "//iam.googleapis.com/projects/531154772515/locations/global/workloadIdentityPools/kanopy-retail-wif-pool/providers/kanopy-retail-provider"

extraVolumeMounts:
  - name: gcp-creds
    mountPath: /etc/gcp
    readOnly: true
  - name: gcp-token
    mountPath: /var/run/service-account
    readOnly: true

# Secret references for sensitive data
envSecrets:
  MONGODB_URI: retail-store-staging
  DATABASE_NAME: retail-store-staging
  OPENAI_API_KEY: retail-store-staging  # If using OpenAI
  STRIPE_SECRET_KEY: retail-store-staging  # If using payment processing

# Environment variables for GCP
env:
  GOOGLE_APPLICATION_CREDENTIALS: /etc/gcp/credential-configuration.json
  GCP_PROJECT_ID: ist-retail-demo
  GCP_LOCATION: us-central1
  # Add retail-specific environment variables
  MONGODB_URI: retail-store-staging  # Reference to Kanopy secret
  DATABASE_NAME: retail-store-staging
  COLLECTION_NAME: retail-store-staging
  # Google Cloud services for retail
  GCP_STORAGE_BUCKET: retail-store-assets
  VERTEX_AI_ENDPOINT: retail-store-assets
  EMBEDDING_ENDPOINT: retail-store-assets
  NEXT_PUBLIC_URL_START: retail-store-assets
  NEXT_PUBLIC_URL_STOP: retail-store-assets